"""App settings, and generation of the ownscribe config they imply.

This app does not reimplement ownscribe's pipeline -- it drives the ownscribe CLI.
One thing it needs (the HuggingFace token for diarization) has no
command-line flag, so it must live in
``~/.config/ownscribe/config.toml``. This module owns writing that file.
"""

from __future__ import annotations

import os
import shutil
import tomllib
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path

import tomli_w

from .diarization import LOCAL_MODEL_TOKEN, has_local_model
from .projects import Project

APP_CONFIG_DIR = Path("~/.config/fly-transcriber").expanduser()
SETTINGS_PATH = APP_CONFIG_DIR / "settings.toml"
TOKEN_PATH = APP_CONFIG_DIR / "hf_token"

OWNSCRIBE_CONFIG_DIR = Path("~/.config/ownscribe").expanduser()
OWNSCRIBE_CONFIG_PATH = OWNSCRIBE_CONFIG_DIR / "config.toml"

#: Env var checked before the on-disk token file.
HF_TOKEN_ENV = "HF_TOKEN"

#: First line of the ownscribe config this app writes. A file that starts with
#: it is ours and is replaced without a backup; anything else was written by
#: hand or by ownscribe, and is backed up once before being replaced.
GENERATED_MARKER = (
    b"# Generated by FLY-transcriber from ~/.config/fly-transcriber/settings.toml\n"
    b"# before every recording. Edit settings there; changes here are overwritten.\n"
)


def ensure_private_dir(path: Path) -> Path:
    """Create ``path`` if needed and make it owner-only.

    Other accounts on the same Mac can otherwise look inside: macOS home
    folders are readable by every local user, so a folder of transcripts,
    settings or tokens should not be.
    """
    path.mkdir(parents=True, exist_ok=True)
    try:
        path.chmod(0o700)
    except OSError:  # e.g. a network volume that has no Unix permissions
        pass
    return path


def write_private(path: Path, data: bytes) -> None:
    """Write ``data`` to ``path`` readable by its owner only, from the first byte."""
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    os.fchmod(fd, 0o600)  # an existing file keeps its mode through O_CREAT
    with os.fdopen(fd, "wb") as f:
        f.write(data)


@dataclass
class Settings:
    """User-facing settings for the recorder.

    ``large-v3`` is the default: roughly 0.8x realtime on Apple Silicon, but the
    smallest model that transcribes languages like Finnish usefully.
    """

    # Transcription
    model: str = "large-v3"
    language: str = ""  # "" = auto-detect; e.g. "fi", "en"
    initial_prompt: str = ""  # domain vocabulary / names to prime Whisper
    hotwords: str = ""

    # Recording
    mic: bool = True
    silence_timeout: int = 300  # seconds; 0 disables auto-stop

    # Diarization
    diarize: bool = True
    min_speakers: int = 0  # 0 = auto
    max_speakers: int = 0

    # Output
    output_dir: str = "~/ownscribe"
    # WAVs are large (~300 MB/hour). Turn this on to re-test diarization
    # settings on the same audio instead of needing a fresh recording.
    keep_recording: bool = False

    # Project destinations offered when a recording stops.
    projects: list[Project] = field(default_factory=list)

    def project(self, name: str) -> Project | None:
        for p in self.projects:
            if p.name == name:
                return p
        return None

    @property
    def resolved_output_dir(self) -> Path:
        return Path(self.output_dir).expanduser()


def load_settings() -> Settings:
    """Load settings, falling back to defaults for anything missing."""
    if not SETTINGS_PATH.exists():
        return Settings()
    with open(SETTINGS_PATH, "rb") as f:
        data = tomllib.load(f)
    known = {f_.name for f_ in Settings.__dataclass_fields__.values()}
    values = {k: v for k, v in data.items() if k in known}
    # Projects are nested tables; rebuild them as dataclasses so unknown or
    # invalid keys from a hand-edited file cannot break startup.
    values["projects"] = [
        Project.from_dict(p) for p in data.get("projects", []) if isinstance(p, dict)
    ]
    return Settings(**values)


def save_settings(settings: Settings) -> None:
    ensure_private_dir(APP_CONFIG_DIR)
    document = asdict(settings)
    document["projects"] = [p.to_dict() for p in settings.projects]
    with open(SETTINGS_PATH, "wb") as f:
        tomli_w.dump(document, f)


def read_hf_token() -> str:
    """Return the HuggingFace token, or an empty string if none is configured.

    Checks ``$HF_TOKEN`` first so a shell-exported token wins, then the token file.
    The token is never written into app settings, which keeps it out of anything
    that might be committed.
    """
    env = os.environ.get(HF_TOKEN_ENV, "").strip()
    if env:
        return env
    if TOKEN_PATH.exists():
        return TOKEN_PATH.read_text(encoding="utf-8").strip()
    return ""


def write_hf_token(token: str) -> Path:
    """Persist the token with owner-only permissions."""
    ensure_private_dir(APP_CONFIG_DIR)
    write_private(TOKEN_PATH, (token.strip() + "\n").encode("utf-8"))
    return TOKEN_PATH


def has_diarization_token() -> bool:
    return bool(read_hf_token()) or has_local_model()


def build_ownscribe_config(settings: Settings) -> dict:
    """Translate app settings into an ownscribe config document."""
    # A local model needs no token, but ownscribe will not diarize without one,
    # so it gets a placeholder. A real token is only needed without the model.
    token = read_hf_token() or (LOCAL_MODEL_TOKEN if has_local_model() else "")

    # Diarization silently produces unlabelled output without a token, so only
    # claim it is enabled when one is actually available.
    diarize_enabled = settings.diarize and bool(token)

    transcription: dict = {
        "model": settings.model,
        "language": settings.language,
    }
    if settings.initial_prompt:
        transcription["initial_prompt"] = settings.initial_prompt
    if settings.hotwords:
        transcription["hotwords"] = settings.hotwords

    return {
        "audio": {
            "backend": "coreaudio",
            "mic": settings.mic,
            "capture_mode": "all",
            "silence_timeout": settings.silence_timeout,
        },
        "transcription": transcription,
        "diarization": {
            "enabled": diarize_enabled,
            "hf_token": token,
            "min_speakers": settings.min_speakers,
            "max_speakers": settings.max_speakers,
            "telemetry": False,
            "device": "auto",  # uses MPS on Apple Silicon when available
        },
        # Summarization is off by design. The transcript is the product; notes
        # are written by the agent in whichever project the meeting is filed to,
        # which handles language and nuance far better than a small local model.
        "summarization": {"enabled": False},
        "output": {
            "dir": settings.output_dir,
            # JSON, not markdown: it is the only format that carries word-level
            # timestamps and per-word speakers. The markdown renderer collapses
            # a segment to a single speaker, hiding turn changes inside it.
            "format": "json",
            "keep_recording": settings.keep_recording,
        },
    }


def apply_ownscribe_config(settings: Settings) -> Path:
    """Write the ownscribe config, backing up a file this app did not write.

    Returns the path written. Runs before every recording, so only a file
    someone else wrote (by hand, or ownscribe's own default) is backed up, once,
    with a timestamp: hand edits are never silently destroyed, and backups of
    this app's own output do not pile up.
    """
    ensure_private_dir(OWNSCRIBE_CONFIG_DIR)
    if OWNSCRIBE_CONFIG_PATH.exists():
        with open(OWNSCRIBE_CONFIG_PATH, "rb") as f:
            ours = f.read(len(GENERATED_MARKER)) == GENERATED_MARKER
        if not ours:
            stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
            backup = OWNSCRIBE_CONFIG_PATH.with_suffix(f".toml.bak-{stamp}")
            shutil.copy2(OWNSCRIBE_CONFIG_PATH, backup)

    document = build_ownscribe_config(settings)
    # The file carries the HF token, so it is owner-readable only.
    write_private(OWNSCRIBE_CONFIG_PATH, GENERATED_MARKER + tomli_w.dumps(document).encode("utf-8"))
    return OWNSCRIBE_CONFIG_PATH
